# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 658c1d9c868a998113169e36c15f5ae2030f393a22b4fe33fd0cc6e59a5827dc7c4285a841ecc55ede16608c8c63dd55c322163b8aedcb4fd4653ae520daef86

test:
  secret_key_base: 94dc53d7acfd28175f5443728338113e42a13836b495e0c34b781b35207d77bf09d8ffdb13b32ef10f95439f53ac6a166d1bec26de94f8b734f606ee0c029eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
